base_domain = "extracttable.com"
free_trail_url = f"https://{base_domain}/camelotpro.html"
purchase_url = f"https://{base_domain}/#pricing"
validate_api_key_url = f"https://validator.{base_domain}"
trigger_url = f"https://trigger.{base_domain}"
job_info_url = f"https://getresult.{base_domain}"
